stages:
- deploy

serverless-projet-stg:
  image: node:20
  stage: deploy
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - node --version
    - npm --version
  script:
    - cd api
    - npm install
    - npm run deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "stg"'
  after_script:
    - echo "Déploiement STG USER terminé"


serverless-projet-prd:
  image: node:20
  stage: deploy
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - cd api
    - node --version
    - npm --version
  script:
    - npm install
    - npm run deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: prd
  after_script:
    - echo "Déploiement PRD USER terminé"


serverless-projet-admin-stg:
  image: node:20
  stage: deploy
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - cd api
    - node --version
    - npm --version
  script:
    - npm install
    - npm run deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "stg"'
  after_script:
    - echo "Déploiement STG ADMIN terminé"


serverless-projet-admin-prd:
  image: node:20
  stage: deploy
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - cd api
    - node --version
    - npm --version
  script:
    - npm install
    - npm run deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: prd
  after_script:
    - echo "Déploiement PRD ADMIN terminé"