services:
  app:
    hostname: serverless_aws
    container_name: serverless_aws
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
