stages:
  - deploy

serverless-projet-assets:
  image: python:3.10
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - apt-get update -y
    - apt-get install -y npm
    - python -m pip install --upgrade pip
    - pip install boto3 python-dotenv
    - node --version
    - npm --version
    - python --version
  script:
    - python infrastructure/scripts/deploy.folder.py serverless_projet_assets
  rules:
    - when: always

serverless-projet-stg:
  image: python:3.10
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - apt-get update -y
    - apt-get install -y npm
    - python -m pip install --upgrade pip
    - pip install boto3 python-dotenv
    - node --version
    - npm --version
    - python --version
  script:
    - cd code/api/my-app
    - npm install
    - python infrastructure/scripts/deploy.front.py serverless_projet_stg
  rules:
    - when: always
  environment:
    name: stg
  after_script:
    - echo "Déploiement STG USER terminé"

serverless-projet-prd:
  image: python:3.10
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - apt-get update -y
    - apt-get install -y npm
    - python -m pip install --upgrade pip
    - pip install boto3 python-dotenv
    - node --version
    - npm --version
    - python --version
  script:
    - cd code/api/my-app
    - npm install
    - python infrastructure/scripts/deploy.front.py serverless_projet_prd
  rules:
    - when: always
  environment:
    name: prd
  after_script:
    - echo "Déploiement PRD USER terminé"

serverless-projet-admin-stg:
  image: python:3.10
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - apt-get update -y
    - apt-get install -y npm
    - python -m pip install --upgrade pip
    - pip install boto3 python-dotenv
    - node --version
    - npm --version
    - python --version
  script:
    - cd code/api/my-app
    - npm install
    - python infrastructure/scripts/deploy.front.py serverless_projet_admin_stg
  rules:
    - when: always
  environment:
    name: stg
  after_script:
    - echo "Déploiement STG ADMIN terminé"

serverless-projet-admin-prd:
  image: python:3.10
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - apt-get update -y
    - apt-get install -y npm
    - python -m pip install --upgrade pip
    - pip install boto3 python-dotenv
    - node --version
    - npm --version
    - python --version
  script:
    - cd code/api/my-app
    - npm install
    - python infrastructure/scripts/deploy.front.py serverless_projet_admin_prd
  rules:
    - when: always
  environment:
    name: prd
  after_script:
    - echo "Déploiement PRD ADMIN terminé"